export const DATA = [
  {
    _id: '1',
    type: 'Opening',
    bondName: 'Omni Capital',
    bondCode: 'OMNI',
    bondInterest: 3,
    unitPrice: 150,
    periodMonth: 12,
    interestRate: 20,
    interestPayment: 'Season',
    interestDay: 365,
    mainPayment: 'End of Term',
    quantity: 50000,
    necessaryAssets: 5000000,
    isClosed: false,
    registeredDate: '2022-02-21',
    registeredEmployee: 'Saruul',
    accumulativeInterest: '',
    bondPeriod: '',
    bondInterestTax: '',
    canRecalled: true,
    lowestQuantity: 20,
    bondId: '1',
    interestPaymentId: '1'
  },
  {
    _id: '2',
    type: 'Closing',
    bondName: 'Chingis',
    bondCode: 'CHINGIS',
    bondInterest: 3,
    unitPrice: 200,
    periodMonth: 12,
    interestRate: 20,
    interestPayment: 'Half Year',
    interestDay: 365,
    mainPayment: 'End of Term',
    quantity: 50000,
    necessaryAssets: 5000000,
    isClosed: false,
    registeredDate: '2022-02-21',
    registeredEmployee: 'Saruul',
    accumulativeInterest: '',
    bondPeriod: '',
    bondInterestTax: '',
    canRecalled: true,
    lowestQuantity: 20,
    bondId: '2',
    interestPaymentId: '2'
  },
  {
    _id: '3',
    type: 'Opening',
    bondName: 'Chingis',
    bondCode: 'CHINGIS',
    bondInterest: 3,
    unitPrice: 150,
    periodMonth: 12,
    interestRate: 20,
    interestPayment: 'End of Term',
    interestDay: 365,
    mainPayment: 'End of Term',
    quantity: 50000,
    necessaryAssets: 5000000,
    isClosed: true,
    registeredDate: '2022-02-21',
    registeredEmployee: 'Saruul',
    accumulativeInterest: '',
    bondPeriod: '',
    bondInterestTax: '',
    canRecalled: true,
    lowestQuantity: 20,
    bondId: '2',
    interestPaymentId: '3'
  },
  {
    _id: '4',
    type: 'Closing',
    bondName: 'Omni Capital',
    bondCode: 'OMNI',
    unitPrice: 150,
    periodMonth: 12,
    interestRate: 20,
    interestPayment: 'Season',
    interestDay: 365,
    mainPayment: 'End of Term',
    quantity: 50000,
    necessaryAssets: 5000000,
    isClosed: false,
    registeredDate: '2022-02-21',
    registeredEmployee: 'Saruul',
    accumulativeInterest: '',
    bondPeriod: '',
    bondInterestTax: '',
    canRecalled: true,
    lowestQuantity: 20,
    bondId: '1',
    interestPaymentId: '1'
  },
  {
    _id: '5',
    type: 'Opening',
    bondName: 'Omni Capital',
    bondCode: 'OMNI',
    unitPrice: 150,
    periodMonth: 12,
    interestRate: 20,
    interestPayment: 'Season',
    interestDay: 365,
    mainPayment: 'End of Term',
    quantity: 50000,
    necessaryAssets: 5000000,
    isClosed: true,
    registeredDate: '2022-02-21',
    registeredEmployee: 'Saruul',
    accumulativeInterest: '',
    bondPeriod: '',
    bondInterestTax: '',
    canRecalled: true,
    lowestQuantity: 20,
    bondId: '1',
    interestPaymentId: '1'
  },
  {
    _id: '6',
    type: 'Closing',
    bondName: 'Omni Capital',
    bondCode: 'OMNI',
    unitPrice: 150,
    periodMonth: 12,
    interestRate: 20,
    interestPayment: 'Season',
    interestDay: 365,
    mainPayment: 'End of Term',
    quantity: 50000,
    necessaryAssets: 5000000,
    isClosed: false,
    registeredDate: '2022-02-21',
    registeredEmployee: 'Saruul',
    accumulativeInterest: '',
    bondPeriod: '',
    bondInterestTax: '',
    canRecalled: true,
    lowestQuantity: 20,
    bondId: '1',
    interestPaymentId: '1'
  }
];

export const TYPE = [
  { label: 'CU', value: 'CU' },
  { label: 'APU', value: 'APU' },
  { label: 'LEND', value: 'LEND' },
  { label: 'GOBI', value: 'GOBI' },
  { label: 'GOLOMT', value: 'GOLOMT' },
  { label: 'TDB', value: 'TDB' },
  { label: 'KHAN', value: 'KHAN' },
  { label: 'ADX', value: 'ADX' },
  { label: 'AAA', value: 'AAA' }
];

export const IPO_COUNTS = {
  CU: '1',
  APU: '1',
  LEND: '0',
  GOBI: '1',
  GOLOMT: '0',
  TDB: '0',
  KHAN: '0',
  ADX: '0',
  AAA: '0'
};

export const LIST = [
  { label: 'Type', name: 'bond.type' },
  { label: 'Bond Name', name: 'bond.bondName' },
  { label: 'Bond code', name: 'bond.bondCode' },
  { label: 'Unit Price', name: 'bond.unitPrice' },
  { label: 'Period by Month', name: 'bond.periodMonth' },
  { label: 'Interest Rate', name: 'bond.interestRate' },
  { label: 'Interest Payment', name: 'bond.interestPayment' },
  { label: 'Interest Day', name: 'bond.interestDay' },
  { label: 'Main Payment', name: 'bond.mainPayment' },
  { label: 'Quantity', name: 'bond.quantity' },
  { label: 'Necessary Assets', name: 'bond.necessaryAssets' }
];

export const CUPON = [
  { label: 'Season', value: 'Season' },
  { label: 'Half Year', value: 'Half Year' },
  { label: 'End of Term', value: 'End of Term' }
];

export const BOND = {
  bondName: 'Omni Capital',
  bondId: '1'
};

export const INTEREST_PAYMENT = {
  interestPayment: 'Season',
  interestPaymentId: '1'
};

export const BOND_DETAIL_ROW = [
  {
    prefix: '232323',
    registry: 'aa12121212',
    lastName: 'Bold',
    firstName: 'Saruul',
    registeredDate: '2022-11-29',
    bondName: 'Omni Capital',
    unitPrice: 200000,
    quantity: 100,
    totalPrice: 20020000,
    periodMonth: 12,
    interestRate: 20,
    interestPayment: 'Season',
    interestDay: 365,
    mainPayment: 'End of Term',
    status: 'Pending',
    bondId: '1',
    interestPaymentId: '1'
  },
  {
    prefix: '232323',
    registry: 'aa12121212',
    lastName: 'Bold',
    firstName: 'Saruul',
    registeredDate: '2022-11-29',
    bondName: 'Omni Capital',
    unitPrice: 200000,
    quantity: 100,
    totalPrice: 20020000,
    periodMonth: 12,
    interestRate: 20,
    interestPayment: 'Season',
    interestDay: 365,
    mainPayment: 'End of Term',
    status: 'Successful',
    bondId: '1',
    interestPaymentId: '1'
  },
  {
    prefix: '232323',
    registry: 'aa12121212',
    lastName: 'Bold',
    firstName: 'Saruul',
    registeredDate: '2022-11-29',
    bondName: 'Omni Capital',
    unitPrice: 200000,
    quantity: 100,
    totalPrice: 20020000,
    periodMonth: 12,
    interestRate: 20,
    interestPayment: 'Season',
    interestDay: 365,
    mainPayment: 'End of Term',
    status: 'Pending',
    bondId: '1',
    interestPaymentId: '1'
  },
  {
    prefix: '232323',
    registry: 'aa12121212',
    lastName: 'Bold',
    firstName: 'Saruul',
    registeredDate: '2022-11-29',
    bondName: 'Omni Capital',
    unitPrice: 200000,
    quantity: 100,
    totalPrice: 20020000,
    periodMonth: 12,
    interestRate: 20,
    interestPayment: 'Season',
    interestDay: 365,
    mainPayment: 'End of Term',
    status: 'Successful',
    bondId: '1',
    interestPaymentId: '1'
  },
  {
    prefix: '232323',
    registry: 'aa12121212',
    lastName: 'Bold',
    firstName: 'Saruul',
    registeredDate: '2022-11-29',
    bondName: 'Omni Capital',
    unitPrice: 200000,
    quantity: 100,
    totalPrice: 20020000,
    periodMonth: 12,
    interestRate: 20,
    interestPayment: 'Half Year',
    interestDay: 365,
    mainPayment: 'End of Term',
    status: 'Pending',
    bondId: '1',
    interestPaymentId: '2'
  },
  {
    prefix: '232323',
    registry: 'aa12121212',
    lastName: 'Bold',
    firstName: 'Saruul',
    registeredDate: '2022-11-29',
    bondName: 'Omni Capital',
    unitPrice: 200000,
    quantity: 100,
    totalPrice: 20020000,
    periodMonth: 12,
    interestRate: 20,
    interestPayment: 'Season',
    interestDay: 365,
    mainPayment: 'End of Term',
    status: 'Successful',
    bondId: '1',
    interestPaymentId: '1'
  },
  {
    prefix: '232323',
    registry: 'aa12121212',
    lastName: 'Bold',
    firstName: 'Saruul',
    registeredDate: '2022-11-29',
    bondName: 'Omni Capital',
    unitPrice: 200000,
    quantity: 100,
    totalPrice: 20020000,
    periodMonth: 12,
    interestRate: 20,
    interestPayment: 'Season',
    interestDay: 365,
    mainPayment: 'End of Term',
    status: 'Pending',
    bondId: '1',
    interestPaymentId: '1'
  }
];

export const BOND_DETAIL_LIST = [
  { label: 'Prefix', name: 'bondDetail.prefix' },
  { label: 'Registry', name: 'bondDetail.registry' },
  { label: 'Last Name', name: 'bondDetail.lastName' },
  { label: 'First Name', name: 'bondDetail.firstName' },
  { label: 'Registered Date', name: 'bondDetail.registeredDate' },
  { label: 'Bond Name', name: 'bondDetail.bondName' },
  { label: 'Unit Price', name: 'bondDetail.unitPrice' },
  { label: 'Quantity', name: 'bondDetail.quantity' },
  { label: 'Total Price', name: 'bondDetail.totalPrice' },
  { label: 'Period by Month', name: 'bondDetail.periodMonth' },
  { label: 'Interest Rate', name: 'bondDetail.interestRate' },
  { label: 'Interest Payment', name: 'bondDetail.interestPayment' },
  { label: 'Interest Day', name: 'bondDetail.interestDay' },
  { label: 'Main Payment', name: 'bondDetail.mainPayment' }
];

export const INTEREST_PAYMENT_ROW = [
  {
    type: 'Opening',
    bondName: 'Omni Capital',
    bondCode: 'OMNI',
    interestPayment: 'Season',
    interestPaymentDay: '2022-12-30',
    paymentAmount: 500000000,
    accumulativeInterest: 100000,
    bondId: '1'
  },
  {
    type: 'Opening',
    bondName: 'Omni Capital',
    bondCode: 'OMNI',
    interestPayment: 'Season',
    interestPaymentDay: '2022-12-30',
    paymentAmount: 500000000,
    accumulativeInterest: 100000,
    bondId: '1'
  },
  {
    type: 'Opening',
    bondName: 'Omni Capital',
    bondCode: 'OMNI',
    interestPayment: 'Season',
    interestPaymentDay: '2022-12-30',
    paymentAmount: 500000000,
    accumulativeInterest: 100000,
    bondId: '1'
  },
  {
    type: 'Opening',
    bondName: 'Omni Capital',
    bondCode: 'OMNI',
    interestPayment: 'Season',
    interestPaymentDay: '2022-12-30',
    paymentAmount: 500000000,
    accumulativeInterest: 100000,
    bondId: '1'
  },
  {
    type: 'Opening',
    bondName: 'Omni Capital',
    bondCode: 'OMNI',
    interestPayment: 'Season',
    interestPaymentDay: '2022-12-30',
    paymentAmount: 500000000,
    accumulativeInterest: 100000,
    bondId: '1'
  }
];

export const INTEREST_PAYMENT_LIST = [
  { label: 'Type', name: 'bond.type' },
  { label: 'Bond Name', name: 'bond.bondName' },
  { label: 'Bond code', name: 'bond.bondCode' },
  { label: 'Interest Payment', name: 'bond.interestPayment' },
  { label: 'Interest Payment Day', name: 'bond.interestPaymentDay' },
  { label: 'Payment Amount', name: 'bondDetail.paymentAmount' },
  { label: 'Accumulative Interest', name: 'bondDetail.accumulativeInterest' }
];

export const INTEREST_PAYMENT_TYPE = [
  { label: 'Season', value: 'Season' },
  { label: 'Half Year', value: 'Half Year' },
  { label: 'End of Term', value: 'End of Term' }
];
